### ISSUE TITLE
No stubs generated for HA 2024.8

### ISSUE THREAD

**Issue by bramstroker** [KapJI/homeassistant-stubs#481]
Just wanted to inform you stub generation is broken for HA 2024.8 looking at the Github actions:
https://github.com/KapJI/homeassistant-stubs/actions

**Comment by bramstroker** [comment]
At least by process of elimination I found out the problem is in recorder.py.

```bash
 ~/code/homeassistant-stubs   poetry run stubgen -o /Users/bram/code/homeassistant-stubs /Users/bram/code/homeassistant-stubs/homeassistant_core/homeassistant/components/recorder
Found existing alias for "poetry run". You should use: "prun"
Traceback (most recent call last):
  File "/Users/bram/Library/Caches/pypoetry/virtualenvs/homeassistant-stubs-EP1-hr2J-py3.12/bin/stubgen", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "mypy/stubgen.py", line 1869, in main
  File "mypy/stubgen.py", line 1677, in generate_stubs
  File "mypy/stubgen.py", line 1647, in generate_stub_for_py_module
  File "mypy/nodes.py", line 369, in accept
  File "mypy/stubgen.py", line 452, in visit_mypy_file
  File "mypy/traverser.py", line 115, in visit_mypy_file
  File "mypy/nodes.py", line 1142, in accept
  File "mypy/stubgen.py", line 718, in visit_class_def
  File "mypy/stubgen.py", line 793, in get_base_types
TypeError: str object expected; got None
```

**Comment by bramstroker** [comment]
Problem is in migration.py

`stubgen /Users/bram/code/ha-core/homeassistant/components/recorder/migration.py`

Did git bisect and found this commit to be the culprit.

https://github.com/home-assistant/core/commit/a22e12dac911b4c752603b6e9c1c8001a7d24589

Not sure which line yet to have a minimal reproduction case.
I'm struggling to get stubgen running locally so I can put in print statement or activate debugger in IDE.

**Comment by bramstroker** [comment]
Made a bug report:
https://github.com/python/mypy/issues/17661

**Comment by bramstroker** [comment]
Might be an idea to exclude recorder/migration.py for stubgeneration, so at least we get the package generation working again. What do you think?

**Comment by KapJI** [comment]
Thanks for creating issue for mypy! I didn't have time to debug it properly but now it seems they have a fix and I'll wait before it gets merged to patch mypy in CI here.

**Comment by bramstroker** [comment]
Thanks. everything working for me again as well.
